=== lgtm-migrator/code-automation-library/bq_application/job/schema_cfg_job.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "$id": "schema_cfg_job.json",
    "type": "object",
    "default": {},
    "title": "Root Schema",
    "required": [
        "name",
        "type",
        "properties",
        "tasks"
    ],
    "properties": {
        "name": {
            "type": "string",
            "default": "",
            "title": "The name of the Job",
            "examples": [
                "GCP_SPINE_OFFER"
            ]
        },
        "description": {
            "type": "string",
            "default": "",
            "title": "Description of the job",
            "examples": [
                "GCP_SPINE_OFFER"
            ]
        },
        "type": {
            "type": "string",
            "default": "",
            "title": "The type of the Job",
            "examples": [
                "BATCH",
                "DAG"
            ]
        },
        "properties": {
            "type": "object",
            "default": {},
            "title": "Allows properties to be passed to target python file."
        },
        "tasks": {
            "type": "array",
            "default": [],
            "title": "A list of tasks to be created in the target DAG"
        },
        "author": {
            "type": "string",
            "default": "",
            "title": "The author of the config",
            "examples": [
                "Sean Conkie"
            ]
        }
    }
}

=== lgtm-migrator/code-automation-library/cfg/job/cfg_gcp_spine_offer.json
{
  "name": "GCP_SPINE_OFFER",
  "description": "Populates portfolio offer tables uk_pub_customer_spine_offer_is",
  "type": "DAG",
  "properties": {
    "tags": ["offer", "customer"],
    "args": {
      "owner": "customerbtprod",
      "email": [
        "sean.conkie@sky.uk"
      ]
    },
    "dataset_source": "uk_arc_chordiant_is",
    "dataset_staging": "uk_pre_customer_spine_offer_is",
    "dataset_publish": "uk_pub_customer_spine_offer_is",
    "gs_source_bucket": "uk_customer_tds_is",
    "imports": []
  },
  "tasks": [
    {
      "task_id": "dim_offer_type",
      "operator": "CREATETABLE",
      "parameters": {
        "key": "value",
        "source_to_target": [
          {
            "name": "id",
            "source_column": "id",
            "source_name": "uk_tds_refdata_eod_is.cc_refdata_bsboffertooffertype",
            "transformation": "",
            "pk": true,
            "hk": false
          },
          {
            "name": "offer_detail_id",
            "source_column": "offerid",
            "source_name": "uk_tds_refdata_eod_is.cc_refdata_bsboffertooffertype",
            "transformation": "",
            "pk": false,
            "hk": false
          },
          {
            "name": "offer_type_id",
            "source_column": "offertypeid",
            "source_name": "uk_tds_refdata_eod_is.cc_refdata_bsboffertooffertype",
            "transformation": "",
            "pk": false,
            "hk": false
          },
          {
            "name": "created_by_id",
            "source_column": "createdby",
            "source_name": "uk_tds_refdata_eod_is.cc_refdata_bsboffertooffertype",
            "transformation": "",
            "pk": false,
            "hk": false
          },
          {
            "name": "created_dt",
            "source_column": "created",
            "source_name": "uk_tds_refdata_eod_is.cc_refdata_bsboffertooffertype",
            "transformation": "",
            "pk": false,
            "hk": false
          },
          {
            "name": "last_modified_dt",
            "source_column": "lastupate",
            "source_name": "uk_tds_refdata_eod_is.cc_refdata_bsboffertooffertype",
            "transformation": "",
            "pk": false,
            "hk": false
          },
          {
            "name": "last_modified_by_id",
            "source_column": "updatedby",
            "source_name": "uk_tds_refdata_eod_is.cc_refdata_bsboffertooffertype",
            "transformation": "",
            "pk": false,
            "hk": false
          },
          {
            "name": "code",
            "source_column": "code",
            "source_name": "uk_tds_refdata_eod_is.cc_refdata_bsboffertype",
            "transformation": "",
            "pk": false,
            "hk": false
          },
          {
            "name": "description",
            "source_column": "description",
            "source_name": "uk_tds_refdata_eod_is.cc_refdata_bsboffertype",
            "transformation": "",
            "pk": false,
            "hk": false
          }
        ],
        "where": [
          {
            "logic_operator": "AND",
            "operator": "!=",
            "fields": [
              "uk_tds_refdata_eod_is.cc_refdata_bsboffertooffertype.rdmaction",
              "'D'"
            ]
          }
        ],
        "joins": [
          {
            "left": "uk_tds_refdata_eod_is.cc_refdata_bsboffertooffertype",
            "right": "uk_tds_refdata_eod_is.cc_refdata_bsboffertype",
            "type": "LEFT",
            "on": [
              {
                "logic_operator": "AND",
                "operator": "=",
                "fields": [
                  "uk_tds_refdata_eod_is.cc_refdata_bsboffertooffertype.offertypeid",
                  "uk_tds_refdata_eod_is.cc_refdata_bsboffertype.id"
                ]
              },
              {
                "logic_operator": "AND",
                "operator": "!=",
                "fields": [
                  "uk_tds_refdata_eod_is.cc_refdata_bsboffertype.rdmaction",
                  "'D'"
                ]
              }
            ]
          }
        ],
        "destination_table": "dim_offer_type",
        "destination_dataset": "uk_pub_customer_spine_offer_is",
        "write_disposition": "WRITETRUNCATE",
        "driving_table": "uk_tds_refdata_eod_is.cc_refdata_bsboffertooffertype",
        "staging_dataset": "uk_pre_customer_spine_offer_is",
        "target_type": "TYPE1"
      },
      "description": "Populates portfolio offer tables uk_pub_customer_spine_offer_is",
      "dependencies": []
    }
  ]
}
