=== lgtm-migrator/code-automation-library/cfg/dag/dag_cfg_schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "$id": "dag_cfg_schema.json",
    "type": "object",
    "default": {},
    "title": "Root Schema",
    "required": [
        "name",
        "dag",
        "args",
        "properties",
        "imports",
        "tasks"
    ],
    "properties": {
        "name": {
            "type": "string",
            "default": "",
            "title": "The name of the DAG",
            "examples": [
                "GCP_SPINE_OFFER"
            ]
        },
        "dag": {
            "type": "object",
            "default": {},
            "title": "Describes the dag",
            "required": [
                "description",
                "tags"
            ],
            "properties": {
                "description": {
                    "type": "string",
                    "default": "",
                    "title": "The description for the DAG to be shown on the webserver",
                    "examples": [
                        "Populates portfolio offer tables uk_pub_customer_spine_offer_is"
                    ]
                },
                "tags": {
                    "type": "array",
                    "default": [],
                    "title": "List of tags to help filtering DAGs in the UI.",
                    "items": {
                        "type": "string",
                        "title": "A tag",
                        "examples": [
                            "offer"
                        ]
                    }
                }
            }
        },
        "args": {
            "type": "object",
            "default": {},
            "title": "A dictionary of default parameters to be used as constructor keyword parameters when initialising operators.",
            "required": [
                "owner"
            ],
            "properties": {
                "owner": {
                    "type": "string",
                    "default": "",
                    "title": "The owner of the DAG - should be the service account used to execute jobs (this will not actually be used to execute jobs)",
                    "examples": [
                        "customerbtprod"
                    ]
                },
                "email": {
                    "type": "array",
                    "default": [],
                    "title": "(Optional) A list of email addresses for Airflow to contact on task failure or retry.",
                    "items": {
                        "type": "string",
                        "default": "",
                        "title": "An email address",
                        "examples": [
                            "sean.conkie@sky.uk"
                        ]
                    }
                }
            },
            "email_on_failure": {
                "type": "boolean",
                "default": [false],
                "title": "(Optional) Email on failure of a task flag."
            },
            "email_on_retry": {
                "type": "boolean",
                "default": [false],
                "title": "(Optional) Email on retry of a task flag."
            },
            "retries": {
                "type": "number",
                "default": [5],
                "title": "(Optional) Maximum number of retries for a task."
            },
            "retry_delay": {
                "type": "number",
                "default": [60],
                "title": "(Optional) The time between each retry, supplied as a number of seconds."
            },
            "on_failure_callback": {
                "type": "string",
                "default": "",
                "title": "(Optional) Invoked when the task fails. Default value for all tasks."
            },
            "on_success_callback": {
                "type": "string",
                "default": "",
                "title": "(Optional) Invoked when the task succeeds. Default value for all tasks."
            },
            "on_retry_callback": {
                "type": "string",
                "default": "",
                "title": "(Optional) Invoked when the task is up for retry. Default value for all tasks."
            },
            "sla_miss_callback": {
                "type": "string",
                "default": "",
                "title": "(Optional) Invoked when a task misses its defined SLA. Default value for all tasks"
            },
            "trigger_rule": {
                "type": "string",
                "default": "all_success",
                "title": "(Optional) Defines what triggers a task. Default 'all_success' requires all dependencies before triggering a task.",
                "examples": [
                    "all_success",
                    "all_failed",
                    "all_done",
                    "one_failed",
                    "one_success",
                    "none_failed",
                    "none_skipped",
                    "none_failed_min_one_success"
                ]
            }
        },
        "properties": {
            "type": "object",
            "default": {},
            "title": "Allows properties to be passed to target python file.",
            "required": [
                "dataset_staging",
                "dataset_publish"
            ],
            "properties": {
                "dataset_staging": {
                    "type": "string",
                    "default": "",
                    "title": "The staging dataset",
                    "examples": [
                        "uk_pre_customer_spine_offer_is"
                    ]
                },
                "dataset_publish": {
                    "type": "string",
                    "default": "",
                    "title": "The publish dataset",
                    "examples": [
                        "uk_pub_customer_spine_offer_is"
                    ]
                }
            }
        },
        "imports": {
            "type": "array",
            "default": [],
            "title": "Allows required packages to be pushed to target python file.",
            "items": {
                "type": "string",
                "default": "",
                "title": "A python package",
                "examples": [
                    "jinja2"
                ]
            }
        },
        "tasks": {
            "type": "array",
            "default": [],
            "title": "A list of tasks to be created in the target DAG"
        }
    }
}

=== lgtm-migrator/code-automation-library/cfg/dag/cfg_gcp_spine_offer.json
{
  "name": "GCP_SPINE_OFFER",
  "dag": {
    "description": "Populates portfolio offer tables uk_pub_customer_spine_offer_is",
    "tags": ["offer", "customer"]
  },
  "args": {
    "owner": "customerbtprod",
    "email": ["sean.conkie@sky.uk"]
  },
  "properties": {
    "dataset_staging": "uk_pre_customer_spine_offer_is",
    "dataset_publish": "uk_pub_customer_spine_offer_is"
  },
  "imports": [],
  "tasks": [
    {
    "task_id": "dim_offer_type",
    "operator": "CreateTable",
    "parameters": {
      "write_disposition": "WRITE_TRUNCATE",
      "destination_table": "dim_offer_type",
      "target_type": 1,
      "driving_table": "uk_tds_refdata_eod_is.cc_refdata_bsboffertooffertype",
      "joins": [
        {
        "right": "uk_tds_refdata_eod_is.cc_refdata_bsboffertype",
        "on": [
          {
          "operator": "=",
          "fields": ["uk_tds_refdata_eod_is.cc_refdata_bsboffertooffertype.offertypeid", "uk_tds_refdata_eod_is.cc_refdata_bsboffertype.id"]
        },
        {
          "operator": "<>",
          "fields": ["uk_tds_refdata_eod_is.cc_refdata_bsboffertype.rdmaction", "'D'"]
        }]
      }],
      "source_to_target": [
        {
          "name": "id",
          "source_name": "uk_tds_refdata_eod_is.cc_refdata_bsboffertooffertype",
          "source_column": "id"
        },
        {
          "name": "dw_last_modified_dt",
          "transformation": "current_timestamp()"
        },
        {
          "name": "offer_detail_id",
          "source_name": "uk_tds_refdata_eod_is.cc_refdata_bsboffertooffertype",
          "source_column": "offerid"
        },
        {
          "name": "offer_type_id",
          "source_name": "uk_tds_refdata_eod_is.cc_refdata_bsboffertooffertype",
          "source_column": "offertypeid"
        },
        {
          "name": "offer_type_id",
          "source_name": "uk_tds_refdata_eod_is.cc_refdata_bsboffertooffertype",
          "source_column": "offertypeid"
        },
        {
          "name": "created_dt",
          "source_name": "uk_tds_refdata_eod_is.cc_refdata_bsboffertooffertype",
          "source_column": "created"
        },
        {
          "name": "created_by_id",
          "source_name": "uk_tds_refdata_eod_is.cc_refdata_bsboffertooffertype",
          "source_column": "createdby"
        },
        {
          "name": "last_modified_dt",
          "source_name": "uk_tds_refdata_eod_is.cc_refdata_bsboffertooffertype",
          "source_column": "lastupdate"
        },
        {
          "name": "last_modified_by_id",
          "source_name": "uk_tds_refdata_eod_is.cc_refdata_bsboffertooffertype",
          "source_column": "updatedby"
        },
        {
          "name": "code",
          "source_name": "uk_tds_refdata_eod_is.cc_refdata_bsboffertype",
          "source_column": "code"
        },
        {
          "name": "description",
          "source_name": "uk_tds_refdata_eod_is.cc_refdata_bsboffertype",
          "source_column": "description"
        }
      ],
      "where": [{
        "operator": "<>",
        "fields": ["uk_tds_refdata_eod_is.cc_refdata_bsboffertooffertype.offertypeid", "'D'"]
      }]
    },
    "dependencies": []
  },
  {
    "task_id": "td_offer_status_core",
    "operator": "CreateTable",
    "parameters": {
      "write_disposition": "WRITE_TRUNCATE",
      "destination_table": "td_offer_status_core",
      "destination_dataset": "uk_pre_customer_spine_offer_is",
      "target_type": 2,
      "history": {
        "partition": [
          {"name": "portfolio_offer_id", "source_name": "uk_tds_chordiant_eod_fc_is.fc_chordiant_bsbportfoliooffer", "source_column": "id"}
        ],
        "driving_column": [
          {"name": "status_code", "source_name": "uk_tds_chordiant_eod_fc_is.fc_chordiant_bsbportfoliooffer", "source_column": "status"},
          {"name": "reason_code", "source_name": "uk_tds_chordiant_eod_fc_is.fc_chordiant_bsbportfoliooffer", "source_column": "statusreasoncode"}
        ],
        "order": [
          {"name": "effective_from_dt", "transformation": "ifnull(uk_tds_chordiant_eod_fc_is.fc_chordiant_bsbportfoliooffer.statuschangeddate,uk_tds_chordiant_eod_fc_is.fc_chordiant_bsbportfoliooffer.effective_from_dt)"},
          {"name": "effective_from_dt_csn_seq", "source_name": "uk_tds_chordiant_eod_fc_is.fc_chordiant_bsbportfoliooffer", "source_column": "effective_from_dt_csn_seq"},
          {"name": "effective_from_dt_seq", "source_name": "uk_tds_chordiant_eod_fc_is.fc_chordiant_bsbportfoliooffer", "source_column": "effective_from_dt_seq"}
        ]
      },
      "driving_table": "uk_tds_chordiant_eod_fc_is.fc_chordiant_bsbportfoliooffer",
      "joins": [
        {
        "right": "uk_tds_chordiant_eod_is.cc_chordiant_picklist",
        "on": [
          {
          "operator": "=",
          "fields": ["uk_tds_chordiant_eod_fc_is.fc_chordiant_bsbportfoliooffer.status", "uk_tds_chordiant_eod_is.cc_chordiant_picklist.code"]
        },
        {
          "operator": "=",
          "fields": ["uk_tds_chordiant_eod_is.cc_chordiant_picklist.logically_deleted", "0"]
        }]
      }],
      "source_to_target": [
        {"name": "portfolio_offer_id", "source_name": "uk_tds_chordiant_eod_fc_is.fc_chordiant_bsbportfoliooffer", "source_column": "id"},
        {"name": "dw_last_modified_dt", "transformation": "current_timestamp()"},
        {"name": "effective_from_dt", "transformation": "ifnull(uk_tds_chordiant_eod_fc_is.fc_chordiant_bsbportfoliooffer.statuschangeddate,uk_tds_chordiant_eod_fc_is.fc_chordiant_bsbportfoliooffer.effective_from_dt)"},
        {"name": "effective_from_dt_csn_seq", "source_name": "uk_tds_chordiant_eod_fc_is.fc_chordiant_bsbportfoliooffer", "source_column": "effective_from_dt_csn_seq"},
        {"name": "effective_from_dt_seq", "source_name": "uk_tds_chordiant_eod_fc_is.fc_chordiant_bsbportfoliooffer", "source_column": "effective_from_dt_seq"},
        {"name": "effective_to_dt", "source_name": "uk_tds_chordiant_eod_fc_is.fc_chordiant_bsbportfoliooffer", "source_column": "statuschangeddate"},
        {"name": "status_code", "source_name": "uk_tds_chordiant_eod_fc_is.fc_chordiant_bsbportfoliooffer", "source_column": "status"},
        {"name": "status", "source_name": "uk_tds_chordiant_eod_is.cc_chordiant_picklist", "source_column": "codedesc"},
        {"name": "reason_code", "source_name": "uk_tds_chordiant_eod_fc_is.fc_chordiant_bsbportfoliooffer", "source_column": "statusreasoncode"},
        {"name": "reason", "source_name": "uk_tds_chordiant_eod_is.cc_chordiant_picklist", "source_column": "codedesc"}              
      ],
      "where": [
        {
        "operator": "=",
        "fields": ["uk_tds_chordiant_eod_fc_is.fc_chordiant_bsbportfoliooffer.logically_deleted", "0"]
      }
    ]
    },
    "dependencies": []
  },
  {
    "task_id": "td_offer_priceable_unit_core",
    "operator": "CreateTable",
    "parameters": {
      "write_disposition": "WRITE_TRUNCATE",
      "destination_table": "td_offer_priceable_unit_core",
      "destination_dataset": "uk_pre_customer_spine_offer_is",
      "target_type": 1,
      "driving_table": "uk_tds_chordiant_eod_is.cc_chordiant_bsbpriceableunit",
      "source_to_target": [
        {"name": "id", "source_name": "uk_tds_chordiant_eod_is.cc_chordiant_bsbpriceableunit", "source_column": "id"},
        {"name": "dw_last_modified_dt", "transformation": "current_timestamp()"},
        {"name": "created_dt", "source_name": "uk_tds_chordiant_eod_is.cc_chordiant_bsbpriceableunit", "source_column": "created"},
        {"name": "created_by_id", "source_name": "uk_tds_chordiant_eod_is.cc_chordiant_bsbpriceableunit", "source_column": "createdby"},
        {"name": "last_modified_dt", "source_name": "uk_tds_chordiant_eod_is.cc_chordiant_bsbpriceableunit", "source_column": "lastupdate"},
        {"name": "last_modified_by_id", "source_name": "uk_tds_chordiant_eod_is.cc_chordiant_bsbpriceableunit", "source_column": "updatedby"},
        {"name": "portfolio_offer_id", "source_name": "uk_tds_chordiant_eod_is.cc_chordiant_bsbpriceableunit", "source_column": "portfolioofferid"},
        {"name": "discounted_priceable_unit_id", "source_name": "uk_tds_chordiant_eod_is.cc_chordiant_bsbpriceableunit", "source_column": "discountedpriceableunitid"},
        {"name": "effective_dt", "source_name": "uk_tds_chordiant_eod_is.cc_chordiant_bsbpriceableunit", "source_column": "effectivedate"},
        {"name": "end_dt", "source_name": "uk_tds_chordiant_eod_is.cc_chordiant_bsbpriceableunit", "source_column": "endate"},
        {"name": "quoted_discount", "transformation": "abs(uk_tds_chordiant_eod_is.cc_chordiant_bsbpriceableunit.quotedprice)"}                             
      ],
      "where": [
        {
        "operator": "=",
        "fields": ["uk_tds_chordiant_eod_is.cc_chordiant_bsbpriceableunit.logically_deleted", "0"]
      }
    ]
    },
    "dependencies": []
  },
{
  "task_id": "td_offer_priceable_unit_soip",
  "operator": "CreateTable",
  "parameters": {
    "sql":"sql/spine_offer_td_offer_priceable_unit_soip.sql",
    "destination_table": "td_offer_priceable_unit_soip",
    "destination_dataset": "uk_pre_customer_spine_offer_is"
  },
  "dependencies": []
},
{
  "task_id": "truncate_dim_offer_priceable_unit",
  "operator": "CreateTable",
  "parameters": {
    "sql":"truncate table uk_pub_customer_spine_offer_is.dim_offer_priceable_unit;",
    "destination_table": "dim_offer_priceable_unit"
  },
  "dependencies": ["td_offer_priceable_unit_soip", "td_offer_priceable_unit_core"]
},
{
  "task_id": "dim_offer_priceable_unit_core",
  "operator": "CreateTable",
  "parameters": {
    "write_disposition": "WRITE_APPEND",
    "destination_table": "dim_offer_priceable_unit",
    "target_type": 1,
    "driving_table": "uk_pre_customer_spine_offer_is.td_offer_priceable_unit_core",
    "source_to_target": [
